# Generated by Django 5.0.3 on 2024-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_book_options_alter_book_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books', verbose_name='Image'),
        ),
    ]
